services:
  postgres:
    image: postgres:16-alpine
    container_name: ufba-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ufba
      POSTGRES_USER: ufba
      POSTGRES_PASSWORD: ufba
    ports:
      - '5436:5432'
    volumes:
      - ufba-postgres-data:/var/lib/postgresql/data

volumes:
  ufba-postgres-data:
