import {
  BadRequestException,
  Injectable,
  NotFoundException,
} from '@nestjs/common';
import type { UserRecord, UserRepository } from './user.repository';

// Only URLs generated by the picker UI (see mobile avatar-picker screen) are
// accepted — this endpoint isn't a general-purpose "save any URL" field.
const ALLOWED_AVATAR_HOST = 'api.dicebear.com';

@Injectable()
export class UsersService {
  constructor(private readonly userRepository: UserRepository) {}

  async getMe(userId: string): Promise<UserRecord> {
    const user = await this.userRepository.findById(userId);
    if (!user) {
      throw new NotFoundException('User not found');
    }
    return user;
  }

  async updateAvatar(userId: string, avatarUrl: string): Promise<void> {
    let url: URL;
    try {
      url = new URL(avatarUrl);
    } catch {
      throw new BadRequestException('avatarUrl must be a valid URL');
    }

    if (url.hostname !== ALLOWED_AVATAR_HOST) {
      throw new BadRequestException(
        `avatarUrl must be hosted on ${ALLOWED_AVATAR_HOST}`,
      );
    }

    await this.userRepository.updateAvatarUrl(userId, avatarUrl);
  }

  /** See UserRepository.deleteAccount — nothing of this student is left. */
  async eraseAccount(userId: string): Promise<void> {
    await this.userRepository.deleteAccount(userId);
  }
}
