export const SIGAA_LINK_REPOSITORY = Symbol('SIGAA_LINK_REPOSITORY');
export const AUDIT_LOGGER = Symbol('AUDIT_LOGGER');
export const USER_REPOSITORY = Symbol('USER_REPOSITORY');
export const HISTORICO_REPOSITORY = Symbol('HISTORICO_REPOSITORY');
