import { PDFParse } from 'pdf-parse';

/**
 * One text run from the transcript PDF, with the position it was painted at.
 *
 * Position is the whole point. The transcript is generated by JasperReports via
 * iText, which paints in an order that dissociates a label from its value — the
 * flat text of any extractor puts "Nome:" three lines away from the name, and
 * the component table's columns interleave. Reading cells off x/y bands is the
 * only way to recover the tabular structure.
 *
 * `fontName` is carried for debugging and fixture inspection only. It must never
 * drive a parsing decision: the transcript's fonts are not embedded, so pdfjs
 * reports `fontFamily: "sans-serif"` for all of them and the only handle that
 * distinguishes the oblique one is a per-document generated id (`g_d0_f3`).
 */
export interface ItemTexto {
  pagina: number;
  x: number;
  y: number;
  texto: string;
  fontName: string;
}

/** The shape this module needs off a pdfjs text item; pdf-parse re-exports pdfjs's own wider type. */
interface ItemPdfJs {
  str?: string;
  transform: number[];
  fontName: string;
}

/**
 * pdf-parse's own `.d.ts` marks `load()` private — it's kept out of the
 * generated docs alongside other helpers — but it is the only way to reach
 * pdfjs's `PDFDocumentProxy`. The public surface (`getText`, `getTable`) only
 * offers flat text and geometry-detected tables, neither of which carries the
 * per-run positions this file exists to capture. Declaring the slice of the
 * shape we actually use, and reaching it through `unknown`, gets that value
 * without either a private-access compile error or an `any` leaking through.
 */
interface DocumentoPdfJs {
  numPages: number;
  getPage(
    pagina: number,
  ): Promise<{ getTextContent(): Promise<{ items: ItemPdfJs[] }> }>;
}
interface PdfParseComCargaDeDocumento {
  load(): Promise<DocumentoPdfJs>;
}

export async function extrairItensHistorico(pdf: Buffer): Promise<ItemTexto[]> {
  const parser = new PDFParse({ data: new Uint8Array(pdf) });
  const itens: ItemTexto[] = [];

  try {
    const documento = await (
      parser as unknown as PdfParseComCargaDeDocumento
    ).load();

    for (let pagina = 1; pagina <= documento.numPages; pagina += 1) {
      const { items } = await (
        await documento.getPage(pagina)
      ).getTextContent();

      for (const item of items) {
        const texto = item.str?.trim();
        if (!texto) {
          continue;
        }
        // transform is the text matrix; [4] and [5] are the translation
        // components, i.e. where on the page this run starts.
        itens.push({
          pagina,
          x: item.transform[4],
          y: item.transform[5],
          texto,
          fontName: item.fontName,
        });
      }
    }
  } finally {
    // pdfjs spawns a worker. Left alive it keeps the Jest process from exiting.
    await parser.destroy();
  }

  return itens;
}
